apiVersion: v1
kind: Service
metadata:
  name: {{ include "Template.fullname" . }}
  labels:
{{ include "Template.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "Template.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}